#ifndef WIN32_INPUT_CODES_HPP
#define WIN32_INPUT_CODES_HPP

#ifdef ST_PLATFORM_WINDOWS

#include <Satoshi/stpch.hpp>

//All the keys and Mouse codes are based at Win32 API

#define ST_MOUSEBUTTON_LEFT VK_LBUTTON
#define ST_MOUSEBUTTON_MIDDLE VK_MBUTTON
#define ST_MOUSEBUTTON_RIGHT VK_RBUTTON
#define ST_MOUSEBUTTON_CANCEL VK_CANCEL
#define ST_MOUSEBUTTON_VUP VK_XBUTTON1
#define ST_MOUSEBUTTON_VDOWN VK_XBUTTON2

#define ST_KEY_ESCAPE VK_ESCAPE
#define ST_KEY_SPACE VK_SPACE
#define ST_KEY_ENTER VK_RETURN
#define ST_KEY_CAPSLOCK VK_CAPITAL
#define ST_KEY_BACKSPACE VK_BACK
#define ST_KEY_TAB VK_TAB

#define ST_KEY_A 0x41
#define ST_KEY_B 0x42
#define ST_KEY_C 0x43
#define ST_KEY_D 0x44
#define ST_KEY_E 0x45
#define ST_KEY_F 0x46
#define ST_KEY_G 0x47
#define ST_KEY_H 0x48
#define ST_KEY_I 0x49
#define ST_KEY_J 0x4A
#define ST_KEY_K 0x4B
#define ST_KEY_L 0x4C
#define ST_KEY_M 0x4D
#define ST_KEY_N 0x4E
#define ST_KEY_O 0x4F
#define ST_KEY_P 0x50
#define ST_KEY_Q 0x51
#define ST_KEY_R 0x52
#define ST_KEY_S 0x53
#define ST_KEY_T 0x54
#define ST_KEY_U 0x55
#define ST_KEY_V 0x56
#define ST_KEY_W 0x57
#define ST_KEY_X 0x58
#define ST_KEY_Y 0x59
#define ST_KEY_Z 0x5A

#define ST_KEY_PLUS VK_OEM_PLUS
#define ST_KEY_COMMA VK_OEM_COMMA
#define ST_KEY_MINUS VK_OEM_MINUS
#define ST_KEY_PERIOD VK_OEM_PERIOD

// this region defines variable keys and the keycode is based in the US keyboard layout
#define ST_KEY_US_SEMICOLON VK_OEM_1
#define ST_KEY_US_QUESTION VK_OEM_2
#define ST_KEY_US_TILDE VK_OEM_3
#define ST_KEY_US_LBRACKET VK_OEM_4
#define ST_KEY_US_BACKSLASH VK_OEM_5
#define ST_KEY_US_RBRACKET VK_OEM_6
#define ST_KEY_US_QUOTE VK_OEM_7
#define ST_KEY_US_SLASH VK_OEM_8
#define ST_KEY_US_ALTBACKSLASH VK_OEM_102

#define ST_KEY_0 0x30
#define ST_KEY_1 0x31
#define ST_KEY_2 0x32
#define ST_KEY_3 0x33
#define ST_KEY_4 0x34
#define ST_KEY_5 0x35
#define ST_KEY_6 0x36
#define ST_KEY_7 0x37
#define ST_KEY_8 0x38
#define ST_KEY_9 0x39

#define ST_KEY_NUMPAD_0 VK_NUMPAD0
#define ST_KEY_NUMPAD_1 VK_NUMPAD1
#define ST_KEY_NUMPAD_2 VK_NUMPAD2
#define ST_KEY_NUMPAD_3 VK_NUMPAD3
#define ST_KEY_NUMPAD_4 VK_NUMPAD4
#define ST_KEY_NUMPAD_5 VK_NUMPAD5
#define ST_KEY_NUMPAD_6 VK_NUMPAD6
#define ST_KEY_NUMPAD_7 VK_NUMPAD7
#define ST_KEY_NUMPAD_8 VK_NUMPAD8
#define ST_KEY_NUMPAD_9 VK_NUMPAD9

#define ST_KEY_DIVIDE VK_DIVIDE
#define ST_KEY_MULTIPLY VK_MULTIPLY
#define ST_KEY_SUBTRACT VK_SUBTRACT
#define ST_KEY_ADD VK_ADD
#define ST_KEY_SEPARATOR VK_SEPARATOR
#define ST_KEY_DECIMAL VK_DECIMAL
#define ST_KEY_CLEAR VK_OEM_CLEAR

#define ST_KEY_ARROW_RIGHT VK_RIGHT
#define ST_KEY_ARROW_UP VK_UP
#define ST_KEY_ARROW_LEFT VK_LEFT
#define ST_KEY_ARROW_DOWN VK_DOWN

#define ST_KEY_INSERT VK_INSERT
#define ST_KEY_DELETE VK_DELETE
#define ST_KEY_HOME VK_HOME
#define ST_KEY_END VK_END
#define ST_KEY_PAGE_UP VK_PRIOR
#define ST_KEY_PAGE_DOWN VK_NEXT

#define ST_KEY_F1 VK_F1
#define ST_KEY_F2 VK_F2
#define ST_KEY_F3 VK_F3
#define ST_KEY_F4 VK_F4
#define ST_KEY_F5 VK_F5
#define ST_KEY_F6 VK_F6
#define ST_KEY_F7 VK_F7
#define ST_KEY_F8 VK_F8
#define ST_KEY_F9 VK_F9
#define ST_KEY_F10 VK_F10
#define ST_KEY_F11 VK_F11
#define ST_KEY_F12 VK_F12
#define ST_KEY_F13 VK_F13
#define ST_KEY_F14 VK_F14
#define ST_KEY_F15 VK_F15
#define ST_KEY_F16 VK_F16
#define ST_KEY_F17 VK_F17
#define ST_KEY_F18 VK_F18
#define ST_KEY_F19 VK_F19
#define ST_KEY_F20 VK_F20
#define ST_KEY_F21 VK_F21
#define ST_KEY_F22 VK_F22
#define ST_KEY_F23 VK_F23
#define ST_KEY_F24 VK_F24

#define ST_KEY_LSHIFT VK_LSHIFT
#define ST_KEY_RSHIFT VK_RSHIFT
#define ST_KEY_LCTRL VK_LCONTROL
#define ST_KEY_RCTRL VK_RCONTROL
#define ST_KEY_LALT VK_LMENU
#define ST_KEY_RALT VK_RMENU

#endif

#endif
